In [245]:
import numpy as np

In [246]:
# Coeff of objective function
z = np.array([7, 6])
z

array([7, 6])

In [247]:
# Coeff of constraints
A = np.array([
    [2, 4],
    [3, 2]
])
A

array([[2, 4],
       [3, 2]])

In [248]:
# RHS of constraints
b = np.array([16, 12])
b

array([16, 12])

In [249]:
m, n = A.shape
m, n

(2, 2)

In [250]:
tableau = np.zeros((m + 1, n + m + 1))
tableau

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [251]:
tableau[:1] = np.concatenate((z, np.zeros(m+1)))

tableau[1:, n:-1] = np.eye(m)
tableau[1:, :n] = A
tableau[1:, -1] = b

tableau

array([[ 7.,  6.,  0.,  0.,  0.],
       [ 2.,  4.,  1.,  0., 16.],
       [ 3.,  2.,  0.,  1., 12.]])

In [252]:
basis = [2, 3]

In [253]:
cb = tableau[0, basis]
cb

array([0., 0.])

In [254]:
zj = np.dot(cb, tableau[1:, :],)
zj

array([0., 0., 0., 0., 0.])

In [255]:
diff = tableau[0] - zj
diff

array([7., 6., 0., 0., 0.])

In [256]:
np.all(diff < 0)

False

In [257]:
pivot_col = np.argmax(diff[:-1]) # Index of max num
pivot_col

0

In [259]:
ratio = tableau[1:, -1] / tableau[1:, pivot_col]
ratio

array([8., 4.])

In [260]:
pivot_row = np.argmin(ratio)
pivot_row

1

In [261]:
basis[pivot_row] = pivot_col
basis

[2, 0]

In [262]:
tableau[pivot_row+1] /= tableau[pivot_row+1, pivot_col]
tableau

array([[ 7.        ,  6.        ,  0.        ,  0.        ,  0.        ],
       [ 2.        ,  4.        ,  1.        ,  0.        , 16.        ],
       [ 1.        ,  0.66666667,  0.        ,  0.33333333,  4.        ]])

In [263]:
for i in range(1, m+1):

    if i == pivot_row + 1:
        continue

    mul = tableau[i][pivot_col]
    tableau[i] -= mul * tableau[pivot_row+1]

tableau

array([[ 7.        ,  6.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  2.66666667,  1.        , -0.66666667,  8.        ],
       [ 1.        ,  0.66666667,  0.        ,  0.33333333,  4.        ]])

In [264]:
cb = tableau[0, basis]
zj = np.dot(cb, tableau[1:, :],)
zj

array([ 7.        ,  4.66666667,  0.        ,  2.33333333, 28.        ])

In [265]:
diff = tableau[0] - zj
diff

array([  0.        ,   1.33333333,   0.        ,  -2.33333333,
       -28.        ])

In [266]:
np.all(diff < 0)

False

In [267]:
tableau

array([[ 7.        ,  6.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  2.66666667,  1.        , -0.66666667,  8.        ],
       [ 1.        ,  0.66666667,  0.        ,  0.33333333,  4.        ]])

In [269]:
opt_sol = np.zeros(n)
opt_sol

array([0., 0.])

In [271]:
basis

[2, 0]

In [272]:
for i in range(n):
    if i in basis:
        row_index = basis.index(i)
        opt_sol[i] = tableau[row_index + 1, -1]

In [275]:
print("\nOptimal Solution for decision variables (x):", opt_sol)
print("Optimal Objective Value (z):", zj[-1])


Optimal Solution for decision variables (x): [4. 0.]
Optimal Objective Value (z): 28.0
