In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

B = np.array([
    [16, 15, 14, 13],
    [12, 11, 10, 9],
    [8, 7, 6, 5],
    [4, 3, 2, 1]
])

In [3]:
def strassen(A: np.ndarray, B: np.ndarray):

    n = A.shape[0]

    if n == 1:
        return A * B

    mid = n // 2

    a = A[:mid, :mid]
    b = A[:mid, mid:]
    c = A[mid:, :mid]
    d = A[mid:, mid:]
    e = B[:mid, :mid]
    f = B[:mid, mid:]
    g = B[mid:, :mid]
    h = B[mid:, mid:]

    p1 = strassen(a, (f - h))
    p2 = strassen((a + b), h)
    p3 = strassen((c + d), e)
    p4 = strassen(d, (g - e))
    p5 = strassen((a + d), (e + h))
    p6 = strassen((b - d), (g + h))
    p7 = strassen((a - c), (e + f))

    c11 = p5 + p4 - p2 + p6
    c12 = p1 + p2
    c21 = p3 + p4
    c22 = p1 + p5 - p3 - p7

    c = np.zeros((n, n))
    c[:mid, :mid] = c11
    c[:mid, mid:] = c12
    c[mid:, :mid] = c21
    c[mid:, mid:] = c22

    return c


In [4]:
strassen(A, B)

array([[ 80.,  70.,  60.,  50.],
       [240., 214., 188., 162.],
       [400., 358., 316., 274.],
       [560., 502., 444., 386.]])

In [5]:
A @ B

array([[ 80,  70,  60,  50],
       [240, 214, 188, 162],
       [400, 358, 316, 274],
       [560, 502, 444, 386]])

In [6]:
import math
a = 33
2 ** math.ceil(math.log2(a))

64

In [7]:
def strassen_pro(A: np.ndarray, B: np.ndarray) -> np.ndarray | None:

    m, n = A.shape
    nB, p = B.shape

    if n != nB:
        print('No you don\'t')
        return None

    pad = 2 ** math.ceil(math.log2(max(m, n, p)))

    A_padded = np.zeros((pad, pad))
    B_padded = np.zeros((pad, pad))

    A_padded[:m, :n] = A
    B_padded[:n, :p] = B

    C_padded = strassen(A_padded, B_padded)
    C = C_padded[:m, :p]

    return C

In [8]:
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

B = np.array([
    [7, 8, 9, 10],
    [11, 12, 13, 14]
])

In [9]:
strassen_pro(A, B)

array([[ 29.,  32.,  35.,  38.],
       [ 65.,  72.,  79.,  86.],
       [101., 112., 123., 134.]])